.github/workflows/msrv.yml
Cargo.toml
src/client.rs
src/eval.rs
src/rules.rs

Specify Minimum Supported Rust Version and dump it down to 1.65.0.
Best reviewed by commit. (Also better to merge or rebase instead of squashing.)

chore: dump MSRV from 1.76.0 down to 1.65.0

---

.github/workflows/publish.yml

automate the publishing step in a cloud environment with a consistent build output
* adds a github step whenever a tag is created. we will create a github "release" and tag together in one step.
* added `CRATES_IO_TOKEN` to the repository's secrets

Add publish github action.

---

.github/workflows/msrv.yml

* Running the `Verify MSRV version` tasks takes ~5 minutes.
* pushes to a pull request branch runs the task twice (once for the PR and once for any `push`)
Logs: https://github.com/Eppo-exp/rust-sdk/actions/runs/9117036192/job/25067006061?pr=5
* caches dependencies of `cargo-msrv` and the `cargo-msrv` binary
* checks if `cargo-msrv` is already installed and uses it
* runs the MSRV task once for a PR and separately on push to `main`
* Ran verify MSRV version task - it was uncached
* Re-run and verified that the tool is cached, went quickly to `verify` step - https://github.com/Eppo-exp/rust-sdk/actions/runs/9117209060/job/25067771911

chore: Cache cargo-msrv tool

---

.gitignore
ruby-sdk/.cargo/config.toml
ruby-sdk/.gitignore
ruby-sdk/Cargo.lock
ruby-sdk/eppo-server-sdk.gemspec
ruby-sdk/ext/eppo_rb/Cargo.toml

**Observation**
While performing validation of the ruby / rust gem I noticed a failure to install the gem in the test server.
🎫 https://linear.app/eppo/issue/FF-2758/ruby-gem-fails-to-install
**Description**
Augments CICD to attempt to install the gem locally so we have a repeatable process to validate its function.

[ruby] fix gem install to use eppo_core from crates.io

---

.github/workflows/publish.yml

🎫 https://linear.app/eppo/issue/FF-2838/fix-cargo-publish-script-to-account-for-eppo-core-and-rust-sdk
Log: https://github.com/Eppo-exp/rust-sdk/actions/runs/10050746627/job/27779182822
**Description**
* Modify the publish script to allow `eppo_core` and `rust-sdk` packages to be published to crate.io
* Allow github action to be run ad-hoc

bug: [allow eppo_core and rust-sdk to be published] (FF-2838)

---

.github/workflows/publish.yml

* Adds ability to publish to ruby gems
* Continues with publish if a dependent version already exists
* Added `RUBYGEMS_API_KEY` environment variable to github repo with permission to publish to https://rubygems.org/gems/eppo-server-sdk
**Testing**
Ran the steps manually: https://rubygems.org/gems/eppo-server-sdk

FF-2857 chore: add publish to rubygems

---

.github/workflows/ci.yml
.github/workflows/msrv.yml
.github/workflows/publish.yml
.gitignore
.gitmodules
Makefile

I'm somewhat tired of `sdk-test-data` updates breaking this SDK unprompted. I also want the ability to apply test-data fixes in branches (e.g., #13 is currently blocked by https://github.com/Eppo-exp/sdk-test-data/pull/49).
Plan:
- add `sdk-test-data` as a submodule so that we can update it when we're ready (instead of updates being pushed on us unexpectedly). (this PR)
- make [Eppo-exp/sdk-test-data](https://github.com/Eppo-exp/sdk-test-data) open a pull request against [Eppo-exp/rust-sdk](https://github.com/Eppo-exp/rust-sdk) when test data change. This will allow our CI validate tests and gives us a chance to adapt our code to new tests before we accept the PR. (Will open a PR on sdk-test-data after this one is merged.)

chore: add sdk-test-data as a submodule

---

.github/workflows/publish.yml
ruby-sdk/eppo-server-sdk.gemspec

Our publish workflow uses Ruby 3.0 to push the gem. Ruby 3.0 ships with RubyGems 3.2.3 which is below our minimum required version (3.3.11).
The version used for publishing does not affect the result of publishing. It's just using the old/unmaintained version of Ruby to do the build and push itself (which also has security concerns).
Update Ruby in publish workflow to 3.3.

chore(ruby): fix ruby publish workflow

---

.github/workflows/publish.yml
ruby-sdk/Gemfile.lock

Workflow step was running in the wrong directory and tried to push a non-existent file

chore(ruby): specify proper location for gem file in publish flow

---

eppo_core/benches/evaluation_details.rs
eppo_core/src/attributes.rs
eppo_core/src/eval/eval_details.rs
eppo_core/src/eval/eval_details_builder.rs
eppo_core/src/eval/eval_rules.rs
eppo_core/src/eval/eval_visitor.rs
eppo_core/src/ufc/models.rs

After benchmarking Rust core and Python SDK, I noticed that rust core performs quite badly on regex conditions. Immediate reaction: regex compilation is kinda slow and we do it on every evaluation call.
This PR moves regex compilation from evaluation phase to parsing, so it happens only once and in background (doesn't slow down evaluation calls).
- This PR adds `ConditionWire` struct, which is the structure we receive from the server (what is transferred "on the wire").
- `Condition` is a new type and optimized for evaluation. There are function to convert back and forth between the two formats. In additional to parsing regex, we also prepare other conditions:
- For comparison operator, we parse version string beforehand
- Check that condition value matches the condition operator (e.g., …

FF-3204 perf: compile regex during parsing

---

eppo_core/benches/evaluation_details.rs
eppo_core/src/configuration_fetcher.rs
eppo_core/src/eval/eval_assignment.rs
eppo_core/src/eval/eval_bandits.rs
eppo_core/src/eval/evaluator.rs
eppo_core/src/eval/mod.rs
eppo_core/src/lib.rs
eppo_core/src/sdk_metadata.rs
python-sdk/src/client.rs
ruby-sdk/ext/eppo_client/src/client.rs
ruby-sdk/lib/eppo_client/client.rb
rust-sdk/Cargo.toml
rust-sdk/src/client.rs
rust-sdk/src/lib.rs
rust-sdk/src/poller.rs

Previously, eppo_core did not set metadata on events correctly (sdk name and version were missing). Python and rust accounted for this separately, and Rust didn't handle it at all.
This PR makes evaluation function take SdkMetadata as a parameter, so it's now impossible to miss.
`now` is not also a parameter, so all evaluation functions are now pure functions without side effects, so we can add time-based tests in the future.
This PR also introduces Evaluator to simplify calling into evaluator functions for upstream SDKs.

refactor(all),fix(rust): introduce Evaluator and handle SdkMetadata

---

rust-sdk/Cargo.toml

3.0.1 hasn't been released yet.

chore: unbump rust-sdk

---

python-sdk/src/configuration.rs

Allow settings bandits configuration. This automatically works for both initial configuration and `Client.set_configuration()`.

feat(python): allow setting bandits configuration

---

ruby-sdk/Cargo.lock
ruby-sdk/Gemfile.lock
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/ext/eppo_client/src/client.rs
ruby-sdk/ext/eppo_client/src/configuration.rs
ruby-sdk/ext/eppo_client/src/gc_lock.rs
ruby-sdk/ext/eppo_client/src/lib.rs
ruby-sdk/lib/eppo_client/client.rb
ruby-sdk/lib/eppo_client/config.rb
ruby-sdk/lib/eppo_client/version.rb
ruby-sdk/spec/configuration_spec.rb
ruby-sdk/spec/eppo_client_spec.rb
ruby-sdk/spec/spec_helper.rb

This PR adds the ability to initialize Ruby SDK in offline mode by passing `poll_interval_seconds: nil` and getting/setting configuration by using `configuration`/`configuration=` methods on `EppoClient`.

feat(ruby): add offline initialization and Configuration API

---

.github/workflows/python.yml
README.md

We had a small incident with `python-sdk@4.0.2` tag pushed without updating the version strings so it tried to publish new artifacts into already released `python-sdk@4.0.1` on pypi. Luckily, none of artifacts were actually pushed because they already exist.
This incident went somewhat unnoticed because there were no GitHub release, just a tag. So I only noticed this when trying to push a new release and found that the tag already exists.
I have rectified this by deleting the old `python-sdk@4.0.2` tag that did not have effect and created a proper release.
This PR is a follow-up and:
- Modifies Python workflow to require a GitHub release, so releases are more visible.
- Adds documentation on the release process.

chore: clarify release process

---

eppo_core/Cargo.toml
python-sdk/Cargo.toml
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/lib/eppo_client/version.rb
rust-sdk/Cargo.toml

Add "vendored" feature flag to eppo_core, which we’re going to reuse in #42.

chore(core): add "vendored" feature flag to eppo_core

---

.github/workflows/python.yml

`release` was accidentally nested under `push`, so release of `python-sdk@4.0.3` didn't go through.

chore(python): fix release workflow trigger

---

.github/workflows/publish.yml
.gitignore
ruby-sdk/Gemfile.lock
ruby-sdk/eppo-server-sdk.gemspec
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/lib/eppo_client/version.rb

Add mising ruby files to gemspec. Since we build the cross platform gems using `rb-sys-dock`, I think `git ls-files` doesn't work because the `.git` directory is not available from the docker container.
Reference: wasmtime gemspec: https://github.com/bytecodealliance/wasmtime-rb/blob/main/wasmtime.gemspec#L21-L28
```
gem install --local pkg/eppo-server-sdk-3.2.2-arm64-darwin.gem
ruby -reppo_client -e "puts EppoClient::VERSION" # => 3.2.2
```

fix: Missing ruby files from native gems

---

.github/workflows/publish.yml
.gitignore
ruby-sdk/Cargo.lock
ruby-sdk/Gemfile.lock
ruby-sdk/README.md
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/lib/eppo_client/client.rb
ruby-sdk/lib/eppo_client/version.rb

rake-compiler puts the shared lib in a subdirectory of `eppo_client` when we build with multiple ruby target versions, so we need to load the lib from the correct subdir.
Again, shamelessly stolen from wasmtime.
Also fixed the CI step so it runs properly (it wasnt)

fix(ruby): Require shared lib from correct subdir

---

.github/workflows/publish.yml
ruby-sdk/Cargo.lock
ruby-sdk/Gemfile.lock
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/lib/eppo_client/version.rb

Looks like we're logging to stderr so grep is not finding out logs. 
Verified this locally:

fix(ruby-ci): Redirect stderr to stdout for grep, bump version

---

ruby-sdk/Gemfile
ruby-sdk/Gemfile.lock

* https://github.com/Eppo-exp/rust-sdk/security/dependabot/4
* https://github.com/Eppo-exp/rust-sdk/security/dependabot/5
* https://github.com/Eppo-exp/rust-sdk/security/dependabot/6
rubocop removes `rexml` dependency in `1.66` (https://github.com/rubocop/rubocop/blob/7b6fdc6f24022e62cb2591f0fab932587da2d9b1/relnotes/v1.66.0.md?plain=1#L45)
Bumped to `1.67` to remove `rexml` from our lockfile.

bump rubocop to 1.67; removes rexml vulnerability (dependabot-6)

---

ruby-sdk/Cargo.lock
ruby-sdk/Gemfile.lock
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/ext/eppo_client/extconf.rb
ruby-sdk/lib/eppo_client/version.rb

In environments for which we don't have prebuilt binaries of the shared eppo client lib, it's built upon running `gem install`, however the resulting file was being placed in the wrong directory.
We want it under `lib/eppo_client/` instead, so that `require_relative 'eppo_client'` works at https://github.com/Eppo-exp/rust-sdk/blob/main/ruby-sdk/lib/eppo_client/client.rb#L13
Tested with a docker container.
Dockerfile:
```
FROM ruby:3.3
WORKDIR /app
RUN apt-get update && apt-get install -y \
git \
build-essential \
curl \
clang \
libclang-dev \
&& rm -rf /var/lib/apt/lists/*
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"
COPY Gemfile Gemfile.lock ./
RUN bundle config force_ruby_platform true
RUN bundle install
COPY …
```

fix(ruby): `eppo_client` shared lib should be under `lib/eppo_client`

---

eppo_core/Cargo.toml
eppo_core/src/configuration_fetcher.rs
eppo_core/src/poller_thread.rs
python-sdk/Cargo.toml
ruby-sdk/Cargo.lock
ruby-sdk/ext/eppo_client/Cargo.toml
rust-sdk/Cargo.toml

To support compiling to a `wasm` target without using feature flags or other conditional compilation, we need to remove usage of the `blocking` client which is not supported.
* Replace usage of `reqwest::blocking` with non-blocking request
* Use `tokio` for async syncronization

convert from reqwest blocking to non-blocking to conform to wasm target

---

.github/workflows/publish.yml

Our smoke test checks for the presence of specific log line. We have changed the default log level to info, so the smoke test now fails.
Re-enable debug logs in CI.

chore(ruby): fix publish workflow by enabling logs

---

Cargo.toml
eppo_core/Cargo.toml
python-sdk/Cargo.toml
python-sdk/pyproject.toml

Free-threaded cpython-3.13 requires pyo3-0.23.2.
serde-pyobject has not been updated yet, so I have submitted a [PR to update it](https://github.com/Jij-Inc/serde-pyobject/pull/13) + pinned my patched version for now.

chore(python): support free-threaded cpython-3.13, drop support for python-3.8

---

.github/workflows/python.yml

`macos-12` runner is deprecated and has stopped working:
Bumped to `macos-13` for `x86_64` and restored `aarch64` build on `macos-14`

chore: upgrade deprecated macos-12 builds to macos-latest

---

.github/dependabot.yml

Dependabot seems to discover subdirectories just fine and opened duplicates (e.g., #97  and #94)

chore(deps): remove subdirectories from dependabot

---

eppo_core/src/poller_thread.rs

Our default jitter value was migrated from Python SDK. However, once we decreased the default poller interval, this made jitter value too high.
With 30s poll interval and 30s jitter, requests are made every 0–30 seconds (with average at 15s). That just doesn’t make much sense.
Decrease jitter value down to 3s, so it polls every 27–30s (avg 28.5s).

FF-3594 Decrease default poller jitter

---

.github/workflows/python.yml
Cargo.toml
eppo_core/Cargo.toml
python-sdk/Cargo.toml
python-sdk/pyproject.toml

Reverts Eppo-exp/eppo-multiplatform#79
I just realized we cannot override dependencies in the workspace because these overrides won't be preserved when we release the crate and will fail to build for our users.
We have to wait till serde-pyobject PR is merged. If that takes too long, we could fork or re-implement our serialization

Revert "chore(python): support free-threaded cpython-3.13, drop support for python-3.8"

---

eppo_core/Cargo.toml
fastly-edge-assignments/Cargo.toml
python-sdk/Cargo.toml
ruby-sdk/ext/eppo_client/Cargo.toml
rust-sdk/Cargo.toml

Would like to push a bunch of releases

chore: bump versions

---

eppo_core/Cargo.toml
fastly-edge-assignments/Cargo.toml
python-sdk/Cargo.toml
ruby-sdk/ext/eppo_client/Cargo.toml
rust-sdk/Cargo.toml

We accidentally included breaking changes in 4.1.1, so bumping the major version now to correct that.

chore: bump major version for core

---

eppo_core/src/eval/eval_precomputed_assignments.rs
eppo_core/src/eval/evaluator.rs
eppo_core/src/ufc/assignment.rs
eppo_core/src/ufc/models.rs
fastly-edge-assignments/src/handlers/handler_assignments.rs

@leoromanovsky this is opened to merge into #81

refactor(core): move PrecomputedConfiguration into core

---

eppo_core/src/poller_thread.rs
python-sdk/Cargo.toml

Customer observed segfaults sometimes during process shutdown.
**Change 1 (Likely Root Cause):**
When the parent process disconnects from the thread’s shared channel, the thread attempts another run. During shutdown, this may cause the thread to access memory that the Python interpreter has already released.
**Change 2:**
Wraps the thread’s execution in a catch_unwind (try/catch equivalent) to handle unexpected panics more gracefully. (edited)
**Change 3: Already merged**
There is an unreleased improvement to the `poller_thread` that handles exceptions from HTTP errors and returns a `Result` - https://github.com/Eppo-exp/eppo-multiplatform/commit/41376295f59ba9f6325c1abe83ebb4f147785d43
The customers' environment did not have this change and it could also be the root cause.
The …

bug: wrap poller thread in `std::panic::catch_unwind` (FF-3468)

---

python-sdk/Cargo.toml

depends on `eppo_core@5.0.0` released https://github.com/Eppo-exp/eppo-multiplatform/releases/tag/eppo_core%405.0.0

bump to python 4.1.4

---

eppo_core/Cargo.toml
eppo_core/src/attributes.rs
eppo_core/src/eval/eval_details.rs
eppo_core/src/events.rs
eppo_core/src/ufc/assignment.rs
package.json
ruby-sdk/Cargo.lock
ruby-sdk/README.md
ruby-sdk/ext/eppo_client/Cargo.toml
ruby-sdk/ext/eppo_client/src/client.rs
ruby-sdk/lib/eppo_client/client.rb

There's an unreleased bug in Ruby whereas get_json_assignment returned two-field object with :raw and :parsed fields instead of just parsed value.
This is due to AttributeValue changing internal format for JSON variant.
Implement Serialize manually for AttributeValue, so only serialize parsed value.
This commit also adds implementation for magnus' IntoValue/TryConvert in eppo core, so we're slightly less reliant on magnus_serde.

fix(rust,ruby): fix serialization format for AttributeValue

---

eppo_core/src/attributes.rs
eppo_core/src/attributes/context_attributes.rs
eppo_core/src/eval/eval_assignment.rs
eppo_core/src/eval/eval_bandits.rs
eppo_core/src/eval/eval_rules.rs
eppo_core/src/eval/mod.rs
eppo_core/src/eval/subject.rs
eppo_core/src/events.rs
eppo_core/src/lib.rs
python-sdk/tests/test_context_attributes.py
rust-sdk/src/lib.rs

Note: the PR is currently open against #123 to minimize diff
So, besides allowing numbers and booleans for categorical attributes this PR basically makes regular `Attributes` aware of their kind (categorical or numeric). So translation between `Attributes` and `ContextAttributes` is more faithful:
```rust
// pseudocode
ContextAttributes {
categorical: {
"string": CategoricalAttribute::String("hello"),
"numeric": CategoricalAttribute::Numeric(42),
"boolean": CategoricalAttribute::Boolean(true),
},
numeric: {
"another_numeric": NumericAttribute::Numeric(12),
},
}.to_generic_attributes() == Attributes {
"string": AttributeValue::Categorical(CategoricalAttribute::String("hello")),
"numeric": AttributeValue::Categorical(CategoricalAttribute::Numeric(42)),
"boolean": …
```

fest(core): support type-preserving numeric and boolean categorical attributes

---

.github/workflows/ruby.yml

YAML interpreted 3.0 as a number and stripped ".0" when installing Ruby. So this caused the latest Ruby version to be installed (instead of 3.0).
With Ruby-3.4 recently released, this broke our CI because ruby-3.4 is not currently supported by our version of rb_sys.

chore(ci): properly quote ruby versions

---

eppo_core/postversion.sh
python-sdk/postversion.sh
ruby-sdk/postversion.sh
rust-sdk/postversion.sh

Accidentally used a non-posix option in #136 and this caused CI fail. Just drop it — shouldn't matter as we're not using pipes anyway

chore: remove -o pipefail as it's not a POSIX shell option

---

ruby-sdk/lib/eppo_client/client.rb

* `return` keyword is optional and can be omitted for the last expression in a method
* proper use of early return guards
* misc cleanup

fix(ruby): Fix some minor Ruby style issues

---

.github/workflows/python.yml

* https://www.maturin.rs/distribution.html#build-wheels
```
Usage: maturin build [OPTIONS] [ARGS]...
Arguments:
[ARGS]...
Rustc flags
Options:
-i, --interpreter [<INTERPRETER>...]
The python versions to build wheels for, given as the executables of interpreters such as `python3.9` or `/usr/bin/python3.8`
-f, --find-interpreter
Find interpreters from the host machine
```
* https://github.com/pydantic/pydantic-core/blob/main/.github/workflows/ci.yml#L474C1-L484C32
We actions log: https://github.com/Eppo-exp/eppo-multiplatform/actions/runs/12680906304/job/35343576093?pr=144

bug: publish macos wheels for python 3.9, 3.10, 3.11 and 3.12 (FF-3786)

---

.github/workflows/python.yml

Did work for (https://github.com/Eppo-exp/eppo-multiplatform/pull/144) but forgot to publish for linux and windows on py3.9+

publish python 3.9+ on linux and windows platforms

---

.github/workflows/python.yml

Reverts Eppo-exp/eppo-multiplatform#146.
#146 seem to have broken `main` and it wasn't necessary as we're building linux correctly for multiple versions, and #146 actually removed builds for PyPy:
and for Windows:

Revert "publish python 3.9+ on linux and windows platforms"

---

.github/workflows/publish.yml

This new workflow should run automatically after eppo_core releases, update Ruby SDK lockfile (updating eppo_core hash to published one), and open a PR.

chore(ci): add a workflow to automatically update ruby lockfile

---

eppo_core/Cargo.toml
eppo_core/src/eval/eval_details_builder.rs
eppo_core/src/events.rs
eppo_core/src/events/event.rs
eppo_core/src/events/event_delivery.rs
eppo_core/src/events/event_dispatcher.rs
eppo_core/src/events/queued_event.rs
eppo_core/src/events/vec_event_queue.rs
ruby-sdk/ext/eppo_client/src/configuration.rs

* Add `QueuedEvent` with `status` and `attempts`
* Add `EventQueue` trait and simple `VecEventQueue` implementation
* Write a few more tests
* Allow returning a batch of events with a given status
* Enforce max queue size constraint
Wrote tests

feat(events): Add `VecEventQueue` abstraction, event status and attempts

---

eppo_core/src/events/event_delivery.rs
eppo_core/src/events/event_dispatcher.rs
eppo_core/src/events/vec_event_queue.rs

Upon a failed event delivery, mark events `status` as failed, increment the `attempts` count and move them to the `failed` queue.
* Wrote a test for `mark_events_as_failed`
* Still planning to write another dispatcher test to ensure events are correctly marked as failed. Will do before merging

chore(events): Mark events as failed

---

.changeset/loud-parents-leave.md
eppo_core/Cargo.toml

When going from `eppo_core 6.0.0->7.0.0` in the precompute server this error was thrown:
```
Updating crates.io index
Locking 2 packages to latest compatible versions
Updating eppo_core v6.0.0 -> v7.0.0
Adding tokio-macros v2.4.0 (available: v2.5.0)
Downloaded eppo_core v7.0.0
Downloaded 1 crate (66.1 KB) in 0.38s
Compiling tokio-macros v2.4.0
Compiling uuid v1.11.0
warning: the `wasm32-wasi` target is being renamed to `wasm32-wasip1` and the `wasm32-wasi` target will be removed from nightly in October 2024 and removed from stable Rust in January 2025
warning: `uuid` (lib) generated 1 warning
Compiling tokio v1.42.0
Compiling eppo_core v7.0.0
warning: `tokio` (lib) generated 1 warning (1 duplicate)
error[E0432]: unresolved import `tokio::sync::mpsc`
--> …
```

add `sync` flag for `tokio` dependency

---

.github/workflows/publish.yml

error thrown:
```
[Invalid workflow file: .github/workflows/publish.yml#L60](https://github.com/Eppo-exp/eppo-multiplatform/actions/runs/12834205830/workflow)
The workflow is not valid. .github/workflows/publish.yml (Line: 60, Col: 5): Unexpected value 'run-on' .github/workflows/publish.yml (Line: 59, Col: 5): Required property is missing: runs-on
```
https://github.com/Eppo-exp/eppo-multiplatform/actions/runs/12834205830

chore: fix typo in publish.yml update_ruby_lockfile step

---

python-sdk/package.json
ruby-sdk/package.json
rust-sdk/package.json

Currently, every change to eppo_core causes a patch version bump and new release for every SDK.
This is somewhat undesirable because changes to eppo_core don't always translate to something meaningful changing in SDKs. Or sometimes, nothing changes at all (e.g., updating pyo3 in eppo_core does not change *anything* for Ruby/Rust SDKs).
I figured that removing eppo_core from dependencies of SDKs should allow us versioning all packages independently. Real dependency version is still bumped from eppo_core's postversion.sh, so this shouldn't change that. But it will allow us to push changes to core that don't cause release of SDKs.
When we want to trigger an SDK release, we should bump it's patch version via a changeset explicitly.
This PR also gets rid of useless "Updated dependencies: …

chore: disconnect SDK releases from eppo_core

---

eppo_core/Cargo.toml
eppo_core/src/event_ingestion/delivery.rs
eppo_core/src/event_ingestion/event_delivery.rs
eppo_core/src/event_ingestion/event_dispatcher.rs

Fixes FF-3849
Enforce that each event's serialized JSON string is under 4096 bytes.
Wrote tests

chore(events): Enforce max event serialized length

---

eppo_core/src/event_ingestion/delivery.rs
eppo_core/src/event_ingestion/event_delivery.rs
eppo_core/src/event_ingestion/event_dispatcher.rs
eppo_core/src/event_ingestion/retry.rs

Addressing feedback here https://github.com/Eppo-exp/eppo-multiplatform/pull/158#discussion_r1926872837 from @rasendubi 
Existing tests

chore(events): Send only retriable events to `retry` component

---

.github/workflows/publish.yml

Without the semicolon after `exit 1`, the shell interprets `}` as a second argument of `exit` and then fails to parse the shell file because it cannot find a closing brace.

chore(ci): add missing semicolon 🤦 

---

.changeset/moody-lions-approve.md
eppo_core/src/event_ingestion/event.rs
eppo_core/src/event_ingestion/event_delivery.rs
eppo_core/src/lib.rs

Event timestamp field should be sent as epoch milliseconds numeric value instead of datetime string.
Wrote a test
FF-3962

fix(events): Ensure Event timestamp is sent as epoch milliseconds

---

ruby-sdk/Cargo.lock

I'm not sure why the CI version bump didn't work this time, had to manually bump it https://github.com/Eppo-exp/eppo-multiplatform/actions/runs/13188399515/job/36816113532

chore(ruby): Bump eppo_core version for next release

---

.changeset/selfish-houses-doubt.md
eppo_core/Cargo.toml
eppo_core/src/configuration.rs
ruby-sdk/ext/eppo_client/Cargo.toml
rust-sdk/Cargo.toml

CI is currently failing because native-tls bumped their MSRV to 1.80.0. Follow them to unblock CI.

chore(core): bump MSRV to 1.80.0

---

.github/workflows/msrv.yml

The MSRV check is failing in all branches.
We agreed to temporarily disable this while we rework the rust version we build with.

temporarily disable msrv check

---

.changeset/cyan-socks-fold.md
eppo_core/src/attributes.rs
eppo_core/src/pyo3.rs
python-sdk/tests/test_assignment_logger.py

Options that are `None` in rust are also `None` in python instead of empty tuples. 
Currently when it is converted back to python it ends up as tuple `()`  which will create an empty tuple object instead. 
Updated test to include checking conversion. 
fixes: https://github.com/Eppo-exp/eppo-multiplatform/issues/211

fix(python): Options that are None are also None in python

---

.github/workflows/ci.yml
.github/workflows/python.yml
.github/workflows/ruby.yml

No need to run, say, Python SDK tests, when making changes to the Ruby SDK. This update limits CI workflows to run only when there are relevant changes.

ci: Add path filtering to GitHub Actions workflows

---

.github/workflows/ci.yml
.github/workflows/python.yml
.github/workflows/ruby.yml

Example sdk-test-data update not triggering CI: https://github.com/Eppo-exp/eppo-multiplatform/pull/237
Note that it triggered Dart SDK checks but not other SDKs. This happens because sdk-test-data is a submodule, so it's treated as a file (not directory) during checking for updates.
This PR removes `/**` from all sdk-test-data patterns (same as in dart.yml), so it should trigger the rest of checks.

chore(ci): fix CI not triggering on sdk-test-data update

---

.changeset/tidy-trees-rhyme.md
elixir-sdk/mix.exs

Having trouble compiling the Elixir SDK in an example app. Hopefully this fixes it:
`could not compile dependency :eppo_sdk, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile eppo_sdk --force", update it with "mix deps.update eppo_sdk" or clean it with "mix deps.clean eppo_sdk"`

[elixir] add files to package

---

.changeset/neat-ghosts-press.md
.github/workflows/ruby.yml
ruby-sdk/Cargo.lock
ruby-sdk/ext/eppo_client/Cargo.toml

[//]: #  (Link to the issue corresponding to this chunk of work)
[//]: # (Describe your changes in detail)
This bumps rb_sys to support latest Ruby version. Also adds prebuilt binaries for Ruby 3.4.
[//]: # (Please describe how you documented the developer impact of your changes; link to PRs or issues or explain why no documentation changes are required)
Changelog entry
[//]: # (Please describe in detail how you tested your changes)
Checked the workflow passes in another branch: https://github.com/Eppo-exp/eppo-multiplatform/actions/runs/14595367078/job/40939859313

chore(ruby): prebuild for 3.4

---

.github/dependabot.yml

Found that dependabot wasn't bumping Ruby SDK lockfile. Adding ruby-sdk directory explicitly should fix that.
Note that this does remove root directory, so the root lockfile will not get updated. That should be fine as it is unused for releases (and we should probably remove it altogether libraries shouldn't normally have lockfiles committed).

chore: make dependabot update nested lock files as well

---

.changeset/cool-points-care.md
.github/workflows/publish.yml
.github/workflows/ruby.yml
ruby-sdk/CHANGELOG.md

[//]: #  (Link to the issue corresponding to this chunk of work)
[//]: #  (Why is this change required? What problem does it solve?)
Followup to #274. Found out that I need to update another workflow to actually enable prebuilt libraries for 3.4.
[//]: # (Describe your changes in detail)
- Actually enable prebuilding binaries for 3.4 on release
- Fix changelog for 3.7.1 as prebuild gem didn't come out
- Add a note in ruby.yml, so it doesn't trip me up again

chore(ruby): actually prebuild for ruby-3.4
